# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main", "WorkFlow" ]
  pull_request:
    branches: [ "main", "WorkFlow" ]

jobs:
  backend:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./APDSPEO/secure-login-portal
    strategy:
      matrix:
        node-version: [20.x, 22.x]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: secure-login-portal/package-lock.json
      - run: npm install
      - run: npm run build --if-present
      - run: npm test

  frontend:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./APDSPEO/secure-login-frontend
    strategy:
      matrix:
        node-version: [20.x, 22.x]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: secure-login-frontend/package-lock.json
      - run: npm install
      - run: npm run build --if-present
      - run: npm test